/* GENERATED by scripts/generate-resume-preview.mjs — do not edit by hand.
 *
 * Re-run `npm run gen:resume-preview` after replacing the resume PDF.
 * `npm run check` fails if sourceSha256 no longer matches the PDF on disk.
 *
 * `src` is hashed on purpose -- see the note in the generator. Never pin
 * this filename anywhere; read it from here.
 */

export const RESUME_PREVIEW = {
  src: "/documents/resume-preview.d9e663b1.webp",
  width: 1500,
  height: 1941,
  /** SHA-256 of the PDF this image was rendered from. */
  sourceSha256: "d9e663b154a357112585dd8a3f8f2c8f3193839afc54f11de4c677267abf7189",
} as const;
