/* GENERATED by scripts/generate-resume-preview.mjs — do not edit by hand.
 *
 * Re-run `npm run gen:resume-preview` after replacing the resume PDF.
 * `npm run check` fails if sourceSha256 no longer matches the PDF on disk.
 */

export const RESUME_PREVIEW = {
  src: "/documents/resume-preview.webp",
  width: 1400,
  height: 1811,
  /** SHA-256 of the PDF this image was rendered from. */
  sourceSha256: "f384c06df923044a3039705714c6aaaf3bfd2b2100bdd8a1b20d157c9ebfdad4",
} as const;
