/* GENERATED by scripts/generate-resume-preview.mjs — do not edit by hand.
 *
 * Re-run `npm run gen:resume-preview` after replacing the resume PDF.
 * `npm run check` fails if sourceSha256 no longer matches the PDF on disk.
 */

export const RESUME_PREVIEW = {
  src: "/documents/resume-preview.webp",
  width: 1400,
  height: 1811,
  /** SHA-256 of the PDF this image was rendered from. */
  sourceSha256: "73e5ca57ece9d0467a6b5c74cbb8466762d89087e8f53072a7964a0423c26362",
} as const;
